<a href="https://colab.research.google.com/github/francois-gonon/POC2PROD_intro/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive; drive.mount('/content/drive')
base_path = 'drive/MyDrive/POC2PROD/' # change to 'drive/MyDrive/POC2PROD/' for Colab or './' if running locally

Mounted at /content/drive

In [2]:
import pandas as pd
import torch
import re
import os
import json
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report
import matplotlib.pyplot as plt

In [3]:
# Load data
df = pd.read_csv(os.path.join(base_path, 'stackoverflow_posts.csv'))
if 'tag_id' not in df.columns:
    tag_map = {t: i for i, t in enumerate(sorted(df['tag_name'].dropna().unique()))}
    df['tag_id'] = df['tag_name'].map(tag_map)
df = df.dropna(subset=['title', 'tag_id'])
df.head()

,post_id,tag_name,tag_id,tag_position,title
0,1987528,php,5,0,Is it possible to execute the procedure of a f...
1,1987531,ruby-on-rails,4984,0,ruby on rails: how to change BG color of optio...
2,1987531,list,5608,1,ruby on rails: how to change BG color of optio...
3,1987531,select,1151,2,ruby on rails: how to change BG color of optio...
4,1987538,c#,9,0,How to read tags out of m4a files in .NET?

In [4]:
# Preprocess text
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    return text
df['clean_title'] = df['title'].astype(str).apply(preprocess_text)
df.head()

,post_id,tag_name,tag_id,tag_position,title,clean_title
0,1987528,php,5,0,Is it possible to execute the procedure of a f...,is it possible to execute the procedure of a f...
1,1987531,ruby-on-rails,4984,0,ruby on rails: how to change BG color of optio...,ruby on rails how to change bg color of option...
2,1987531,list,5608,1,ruby on rails: how to change BG color of optio...,ruby on rails how to change bg color of option...
3,1987531,select,1151,2,ruby on rails: how to change BG color of optio...,ruby on rails how to change bg color of option...
4,1987538,c#,9,0,How to read tags out of m4a files in .NET?,how to read tags out of ma files in net

In [5]:
# Remove rare labels globally first
label_counts = df['tag_id'].value_counts()
rare_labels = label_counts[label_counts < 6].index
if len(rare_labels) > 0:
    df = df[~df['tag_id'].isin(rare_labels)]

# Split data for stage 1: only tag_position = 0
df_stage1 = df[df['tag_position'] == 0].copy()
label_counts_stage1 = df_stage1['tag_id'].value_counts()
rare_labels_stage1 = label_counts_stage1[label_counts_stage1 < 6].index
if len(rare_labels_stage1) > 0:
    df_stage1 = df_stage1[~df_stage1['tag_id'].isin(rare_labels_stage1)]
train_df_stage1, test_df_stage1 = train_test_split(df_stage1, test_size=0.2, stratify=df_stage1['tag_id'], random_state=42)

# Split data for stage 2: full dataset
train_df_full, test_df_full = train_test_split(df, test_size=0.2, stratify=df['tag_id'], random_state=42)

In [6]:
# Load tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
label_dict = {label: i for i, label in enumerate(train_df_stage1['tag_id'].unique())}
num_labels = len(label_dict)
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=num_labels)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [7]:
# Create dataset class
class Dataset(torch.utils.data.Dataset):
    def __init__(self, df, tokenizer, label_dict):
        self.df = df
        self.tokenizer = tokenizer
        self.label_dict = label_dict
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        text = self.df.iloc[idx]['clean_title']
        label = self.label_dict[self.df.iloc[idx]['tag_id']]
        encoding = self.tokenizer(text, truncation=True, padding='max_length', max_length=128, return_tensors='pt')
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

train_dataset_stage1 = Dataset(train_df_stage1, tokenizer, label_dict)
test_dataset_stage1 = Dataset(test_df_stage1, tokenizer, label_dict)

In [8]:
# Stage 1: Train on tag_position = 0 subset
training_args = TrainingArguments(
    output_dir=os.path.join(base_path, 'results_stage1'),
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    logging_dir=os.path.join(base_path, 'logs_stage1'),
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_stage1,
    eval_dataset=test_dataset_stage1,
)
trainer.train()

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: francoisg (francoisg-epf-engineering-school) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=618, training_loss=2.6865898798970345, metrics={'train_runtime': 454.56, 'train_samples_per_second': 21.753, 'train_steps_per_second': 1.36, 'total_flos': 650860191424512.0, 'train_loss': 2.6865898798970345, 'epoch': 3.0})

In [9]:
# Evaluate stage 1
predictions = trainer.predict(test_dataset_stage1)
pred_labels = [list(label_dict.keys())[p] for p in predictions.predictions.argmax(axis=1)]
true_labels = test_df_stage1['tag_id'].tolist()
acc = accuracy_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels, average='weighted')
print(f'Stage 1 - Test acc: {acc:.4f}, f1: {f1:.4f}')
print(classification_report(true_labels, pred_labels))

# Save stage 1 model
model.save_pretrained(os.path.join(base_path, 'model_stage1'))
tokenizer.save_pretrained(os.path.join(base_path, 'model_stage1'))
with open(os.path.join(base_path, 'model_stage1', 'label_dict.json'), 'w') as f:
    json.dump({str(k): v for k, v in label_dict.items()}, f)

Stage 1 - Test acc: 0.4551, f1: 0.3875
              precision    recall  f1-score   support

           1       0.17      0.04      0.06        25
           2       0.53      0.53      0.53        17
           3       0.52      0.56      0.54        45
           4       0.00      0.00      0.00         8
           5       0.58      0.65      0.62        92
           8       0.00      0.00      0.00        15
           9       0.32      0.67      0.44       101
          10       0.12      0.05      0.08        37
          12       0.00      0.00      0.00         7
          16       0.55      0.66      0.60        44
          17       0.45      0.75      0.56        71
          18       0.00      0.00      0.00         4
          19       0.00      0.00      0.00         5
          21       0.00      0.00      0.00        10
          22       0.37      0.55      0.44        20
          28       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         4
          33       0.00      0.00      0.00         2
          38       0.43      0.33      0.38         9
          41       0.00      0.00      0.00         5
          48       0.00      0.00      0.00         1
          53       0.00      0.00      0.00         3
          58       0.00      0.00      0.00         3
          63       0.50      0.20      0.29         5
          64       0.00      0.00      0.00         7
          72       0.00      0.00      0.00        11
          80       0.00      0.00      0.00         2
          96       0.31      0.47      0.37        30
         118       1.00      0.40      0.57         5
         119       0.80      0.80      0.80         5
         129       0.00      0.00      0.00         1
         136       0.00      0.00      0.00         2
         154       0.56      0.79      0.65        47
         194       0.00      0.00      0.00         2
         243       0.67      0.75      0.71         8
         248       0.00      0.00      0.00         5
         299       0.00      0.00      0.00         5
         352       0.00      0.00      0.00         3
         355       0.00      0.00      0.00         1
         363       0.00      0.00      0.00         2
         369       0.00      0.00      0.00         1
         370       0.00      0.00      0.00         1
         371       1.00      0.50      0.67         2
         376       0.50      1.00      0.67         3
         378       1.00      0.09      0.17        11
         382       0.00      0.00      0.00         1
         387       0.00      0.00      0.00         2
         456       0.00      0.00      0.00         1
         463       0.00      0.00      0.00         1
         470       0.00      0.00      0.00        10
         522       0.00      0.00      0.00         2
         526       0.00      0.00      0.00         1
         580       0.44      1.00      0.62         4
         598       0.00      0.00      0.00         2
         669       0.00      0.00      0.00         4
         752       0.00      0.00      0.00         1
         820       0.73      0.73      0.73        26
         908       0.00      0.00      0.00         1
         984       0.00      0.00      0.00         3
         994       0.00      0.00      0.00         5
        1158       0.00      0.00      0.00         2
        1381       0.00      0.00      0.00         1
        1386       0.53      0.60      0.56        15
        1819       0.00      0.00      0.00         1
        2620       0.00      0.00      0.00         1
        3143       0.00      0.00      0.00         2
        3262       0.00      0.00      0.00         1
        4301       0.00      0.00      0.00         1
        4527       0.00      0.00      0.00         2
        4984       0.54      0.65      0.59        20
        4985       0.00      0.00      0.00         1
        5210       0.00      0.00      0.00         1
        7003       0.00      0.00      0.00        10
       14012       0.00      0.00      0.00         3
       32472       0.00      0.00      0.00         2
       33126       0.00      0.00      0.00         1
       33953       0.00      0.00      0.00         5
       34469       0.00      0.00      0.00         1
       58338       0.00      0.00      0.00         1

    accuracy                           0.46       824
   macro avg       0.16      0.16      0.15       824
weighted avg       0.37      0.46      0.39       824

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [10]:
# Update label dict for full dataset
label_dict_full = {label: i for i, label in enumerate(train_df_full['tag_id'].unique())}
num_labels_full = len(label_dict_full)

# Load new model for stage 2
model_stage2 = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=num_labels_full)

train_dataset_full = Dataset(train_df_full, tokenizer, label_dict_full)
test_dataset_full = Dataset(test_df_full, tokenizer, label_dict_full)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [11]:
# Stage 2: Train on full dataset
training_args_full = TrainingArguments(
    output_dir=os.path.join(base_path, 'results_stage2'),
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    logging_dir=os.path.join(base_path, 'logs_stage2'),
)
trainer_full = Trainer(
    model=model_stage2,
    args=training_args_full,
    train_dataset=train_dataset_full,
    eval_dataset=test_dataset_full,
)
trainer_full.train()

TrainOutput(global_step=1353, training_loss=4.443111715718542, metrics={'train_runtime': 481.9377, 'train_samples_per_second': 44.863, 'train_steps_per_second': 2.807, 'total_flos': 1426433172132096.0, 'train_loss': 4.443111715718542, 'epoch': 3.0})

In [12]:
# Evaluate stage 2
predictions_full = trainer_full.predict(test_dataset_full)
pred_labels_full = [list(label_dict_full.keys())[p] for p in predictions_full.predictions.argmax(axis=1)]
true_labels_full = test_df_full['tag_id'].tolist()
acc_full = accuracy_score(true_labels_full, pred_labels_full)
f1_full = f1_score(true_labels_full, pred_labels_full, average='weighted')
print(f'Stage 2 - Test acc: {acc_full:.4f}, f1: {f1_full:.4f}')
print(classification_report(true_labels_full, pred_labels_full))

# Save stage 2 model
model_stage2.save_pretrained(os.path.join(base_path, 'model_stage2'))
tokenizer.save_pretrained(os.path.join(base_path, 'model_stage2'))
with open(os.path.join(base_path, 'model_stage2', 'label_dict.json'), 'w') as f:
    json.dump({str(k): v for k, v in label_dict_full.items()}, f)

Stage 2 - Test acc: 0.2309, f1: 0.1475
              precision    recall  f1-score   support

           1       0.11      0.09      0.09        47
           2       0.18      0.27      0.22        33
           3       0.22      0.39      0.28        54
           4       0.00      0.00      0.00        20
           5       0.28      0.55      0.37        94
           8       0.00      0.00      0.00        21
           9       0.15      0.60      0.24       101
          10       0.08      0.16      0.11        38
          12       0.24      0.36      0.29        14
          16       0.27      0.66      0.39        47
          17       0.25      0.65      0.36        72
          18       0.00      0.00      0.00        12
          19       0.00      0.00      0.00        12
          21       0.30      0.45      0.36        31
          22       0.17      0.56      0.27        27
          23       0.00      0.00      0.00         4
          27       0.00      0.00      0.00         3
          28       0.00      0.00      0.00         8
          30       0.00      0.00      0.00        11
          33       0.00      0.00      0.00         3
          34       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         4
          38       0.32      0.73      0.44        11
          41       0.00      0.00      0.00        12
          48       0.00      0.00      0.00         3
          49       0.00      0.00      0.00         6
          53       0.00      0.00      0.00         9
          57       0.00      0.00      0.00         1
          58       0.00      0.00      0.00         7
          61       0.00      0.00      0.00         3
          63       0.20      0.20      0.20         5
          64       0.00      0.00      0.00        10
          72       0.00      0.00      0.00        18
          73       0.00      0.00      0.00         2
          80       0.00      0.00      0.00         5
          87       0.00      0.00      0.00         2
          96       0.18      0.20      0.19        46
         110       0.00      0.00      0.00         2
         114       0.00      0.00      0.00         9
         115       0.00      0.00      0.00         2
         118       0.00      0.00      0.00         6
         119       0.00      0.00      0.00         6
         121       0.00      0.00      0.00         4
         125       0.00      0.00      0.00         2
         129       0.00      0.00      0.00         3
         134       0.00      0.00      0.00         2
         136       0.00      0.00      0.00         6
         137       0.00      0.00      0.00         8
         139       0.00      0.00      0.00        11
         142       0.00      0.00      0.00         1
         146       0.00      0.00      0.00         3
         148       0.00      0.00      0.00         3
         153       0.00      0.00      0.00         2
         154       0.29      0.74      0.42        50
         162       0.00      0.00      0.00         2
         173       0.00      0.00      0.00         4
         183       0.00      0.00      0.00         4
         186       0.00      0.00      0.00         2
         190       0.00      0.00      0.00         3
         194       0.00      0.00      0.00         4
         201       0.00      0.00      0.00         4
         215       0.00      0.00      0.00         3
         219       0.00      0.00      0.00         2
         220       0.00      0.00      0.00         2
         243       0.41      0.86      0.56        14
         247       0.00      0.00      0.00         1
         248       0.00      0.00      0.00         8
         256       0.00      0.00      0.00         3
         259       0.00      0.00      0.00         5
         261       0.00      0.00      0.00         1
         272       0.00      0.00      0.00         2
         276       0.00      0.00      0.00         3
         277       0.00      0.00      0.00         5
         279       0.00      0.00      0.00         3
         290       0.00      0.00      0.00         3
         292       0.00      0.00      0.00         4
         299       0.00      0.00      0.00         8
         317       0.00      0.00      0.00         2
         343       0.00      0.00      0.00         2
         348       0.00      0.00      0.00         2
         352       0.00      0.00      0.00         6
         353       0.00      0.00      0.00         1
         355       0.00      0.00      0.00         4
         360       0.00      0.00      0.00         2
         363       0.00      0.00      0.00        13
         364       0.00      0.00      0.00         2
         365       0.00      0.00      0.00         3
         367       0.00      0.00      0.00         2
         369       0.00      0.00      0.00         6
         370       0.00      0.00      0.00         2
         371       1.00      0.67      0.80         3
         376       0.00      0.00      0.00         6
         378       0.33      0.76      0.46        17
         382       0.00      0.00      0.00         3
         387       1.00      0.33      0.50         3
         390       0.00      0.00      0.00         2
         444       0.00      0.00      0.00         2
         450       0.00      0.00      0.00         1
         456       0.00      0.00      0.00         3
         457       0.00      0.00      0.00         1
         463       0.00      0.00      0.00         2
         470       0.41      0.41      0.41        22
         488       0.00      0.00      0.00         2
         506       0.00      0.00      0.00         3
         519       0.00      0.00      0.00         1
         522       0.00      0.00      0.00         4
         526       0.00      0.00      0.00         3
         529       0.00      0.00      0.00         2
         531       0.00      0.00      0.00         2
         538       0.00      0.00      0.00         2
         543       0.00      0.00      0.00         3
         552       0.00      0.00      0.00         1
         580       0.56      0.71      0.62         7
         581       0.00      0.00      0.00         2
         598       0.00      0.00      0.00         8
         603       0.00      0.00      0.00         2
         607       0.00      0.00      0.00         2
         641       0.00      0.00      0.00         2
         644       0.00      0.00      0.00         2
         647       0.00      0.00      0.00         3
         658       0.00      0.00      0.00         1
         669       0.00      0.00      0.00         5
         688       0.00      0.00      0.00         3
         691       0.00      0.00      0.00         4
         724       0.00      0.00      0.00         2
         725       0.00      0.00      0.00         1
         729       0.00      0.00      0.00         2
         733       0.00      0.00      0.00         1
         752       0.00      0.00      0.00         4
         773       0.00      0.00      0.00         1
         794       0.00      0.00      0.00         2
         816       0.00      0.00      0.00         2
         820       0.39      0.64      0.49        44
         824       0.00      0.00      0.00         1
         829       0.00      0.00      0.00         4
         848       0.00      0.00      0.00         1
         852       0.00      0.00      0.00         1
         854       0.50      0.67      0.57         3
         859       0.00      0.00      0.00         1
         862       0.00      0.00      0.00         1
         865       0.00      0.00      0.00         6
         868       0.00      0.00      0.00         2
         889       0.00      0.00      0.00         7
         890       0.00      0.00      0.00         1
         904       0.00      0.00      0.00         2
         908       0.00      0.00      0.00         9
         916       0.00      0.00      0.00         1
         926       0.00      0.00      0.00         3
         930       0.00      0.00      0.00         3
         938       0.00      0.00      0.00         1
         942       0.00      0.00      0.00         2
         965       0.00      0.00      0.00         2
         984       0.00      0.00      0.00         8
         994       0.00      0.00      0.00         9
        1065       0.00      0.00      0.00         1
        1066       0.00      0.00      0.00         1
        1082       0.00      0.00      0.00         4
        1117       0.00      0.00      0.00         3
        1124       0.00      0.00      0.00         3
        1125       0.00      0.00      0.00         3
        1137       0.00      0.00      0.00         2
        1141       0.00      0.00      0.00         2
        1151       0.00      0.00      0.00         2
        1158       0.00      0.00      0.00         4
        1169       0.00      0.00      0.00         1
        1189       0.00      0.00      0.00         4
        1190       0.00      0.00      0.00         2
        1198       0.00      0.00      0.00         2
        1201       0.00      0.00      0.00         1
        1208       0.00      0.00      0.00         2
        1211       0.00      0.00      0.00         4
        1227       0.00      0.00      0.00         3
        1231       0.00      0.00      0.00         1
        1235       0.00      0.00      0.00         2
        1263       0.00      0.00      0.00         5
        1292       0.00      0.00      0.00         1
        1301       0.00      0.00      0.00         1
        1307       0.00      0.00      0.00         2
        1357       0.00      0.00      0.00         4
        1362       0.00      0.00      0.00         1
        1381       0.00      0.00      0.00        11
        1386       0.40      0.60      0.48        20
        1435       0.00      0.00      0.00         6
        1449       0.00      0.00      0.00         3
        1467       0.00      0.00      0.00         1
        1469       0.00      0.00      0.00         2
        1477       0.00      0.00      0.00         3
        1478       0.00      0.00      0.00         3
        1508       0.00      0.00      0.00         6
        1531       0.00      0.00      0.00         1
        1554       0.00      0.00      0.00         2
        1583       0.00      0.00      0.00         2
        1602       0.00      0.00      0.00         3
        1603       0.00      0.00      0.00         1
        1608       0.00      0.00      0.00         2
        1644       0.00      0.00      0.00         3
        1646       0.00      0.00      0.00         1
        1655       0.00      0.00      0.00         2
        1694       0.00      0.00      0.00         1
        1695       0.00      0.00      0.00         3
        1702       0.00      0.00      0.00         2
        1704       0.00      0.00      0.00         2
        1709       0.00      0.00      0.00         2
        1759       0.00      0.00      0.00         2
        1763       0.00      0.00      0.00         3
        1817       0.00      0.00      0.00         1
        1819       0.00      0.00      0.00         3
        1834       0.00      0.00      0.00         2
        1914       0.00      0.00      0.00         2
        1926       0.00      0.00      0.00         2
        1931       0.00      0.00      0.00         3
        2027       0.00      0.00      0.00         2
        2097       0.00      0.00      0.00         1
        2167       0.00      0.00      0.00         2
        2175       0.00      0.00      0.00         1
        2176       0.00      0.00      0.00         2
        2177       0.00      0.00      0.00         1
        2218       0.00      0.00      0.00         4
        2314       0.00      0.00      0.00         2
        2387       0.00      0.00      0.00         1
        2433       0.00      0.00      0.00         3
        2443       0.00      0.00      0.00         2
        2494       0.00      0.00      0.00         1
        2512       0.00      0.00      0.00         2
        2535       0.00      0.00      0.00         3
        2556       0.00      0.00      0.00         2
        2579       0.00      0.00      0.00         5
        2596       0.00      0.00      0.00         2
        2620       0.00      0.00      0.00         3
        2631       0.00      0.00      0.00         2
        2678       0.00      0.00      0.00         2
        2719       0.00      0.00      0.00         1
        2740       0.00      0.00      0.00         2
        2775       0.00      0.00      0.00         1
        2780       0.00      0.00      0.00         2
        2823       0.00      0.00      0.00         2
        2857       0.00      0.00      0.00         3
        2990       0.00      0.00      0.00         2
        3054       0.00      0.00      0.00         2
        3143       0.00      0.00      0.00         4
        3227       0.00      0.00      0.00         2
        3262       0.00      0.00      0.00         2
        3437       0.00      0.00      0.00         2
        3550       0.00      0.00      0.00         2
        3586       0.00      0.00      0.00         2
        3600       0.00      0.00      0.00         1
        3626       0.00      0.00      0.00         2
        3737       0.00      0.00      0.00         2
        3849       0.00      0.00      0.00         1
        3854       0.00      0.00      0.00         2
        3946       0.00      0.00      0.00         2
        3988       0.00      0.00      0.00         4
        4196       0.00      0.00      0.00         4
        4209       0.00      0.00      0.00         2
        4301       0.00      0.00      0.00         2
        4446       0.00      0.00      0.00         1
        4452       0.00      0.00      0.00         1
        4520       0.00      0.00      0.00         1
        4527       0.00      0.00      0.00         7
        4545       0.00      0.00      0.00         2
        4574       0.00      0.00      0.00         1
        4747       0.00      0.00      0.00         1
        4898       0.00      0.00      0.00         3
        4948       0.00      0.00      0.00         2
        4984       0.27      0.48      0.34        21
        4985       0.00      0.00      0.00         8
        5002       0.00      0.00      0.00         2
        5029       0.00      0.00      0.00         2
        5036       0.00      0.00      0.00         2
        5052       0.00      0.00      0.00         1
        5142       0.00      0.00      0.00         4
        5187       0.00      0.00      0.00         5
        5210       0.00      0.00      0.00         4
        5263       0.00      0.00      0.00         3
        5310       0.00      0.00      0.00         4
        5382       0.00      0.00      0.00         1
        5486       0.00      0.00      0.00         2
        5569       0.00      0.00      0.00         3
        5608       0.00      0.00      0.00         2
        5617       0.00      0.00      0.00         2
        5647       0.00      0.00      0.00         2
        5876       0.00      0.00      0.00         1
        5909       0.00      0.00      0.00         2
        5910       0.00      0.00      0.00         2
        6051       0.00      0.00      0.00         1
        6268       0.00      0.00      0.00         2
        6439       0.00      0.00      0.00         2
        6557       0.00      0.00      0.00         1
        6752       0.00      0.00      0.00         1
        6941       0.00      0.00      0.00         2
        6981       0.00      0.00      0.00         4
        7002       0.00      0.00      0.00         3
        7003       0.04      0.04      0.04        24
        7407       0.00      0.00      0.00         1
        7715       0.00      0.00      0.00         1
        8944       0.00      0.00      0.00         3
        9002       0.00      0.00      0.00         2
       10052       0.00      0.00      0.00         1
       10401       0.00      0.00      0.00         1
       10580       0.00      0.00      0.00         1
       10593       0.00      0.00      0.00         1
       10742       0.00      0.00      0.00         2
       11215       0.00      0.00      0.00         1
       12193       0.00      0.00      0.00         1
       12280       0.00      0.00      0.00         1
       12752       0.00      0.00      0.00         1
       13423       0.00      0.00      0.00         2
       13591       0.11      1.00      0.20         1
       13613       0.00      0.00      0.00         1
       14012       0.00      0.00      0.00        11
       14456       0.00      0.00      0.00         1
       14642       0.00      0.00      0.00         1
       15080       0.00      0.00      0.00         2
       19717       0.00      0.00      0.00         1
       21111       0.00      0.00      0.00         1
       23087       0.00      0.00      0.00         4
       26050       0.00      0.00      0.00         2
       26084       0.00      0.00      0.00         2
       27300       0.00      0.00      0.00         2
       27758       0.00      0.00      0.00         2
       30408       0.00      0.00      0.00         2
       31481       0.00      0.00      0.00         1
       32472       0.00      0.00      0.00         7
       33126       0.00      0.00      0.00         6
       33953       0.00      0.00      0.00         8
       34469       0.00      0.00      0.00         5
       34595       0.00      0.00      0.00         3
       34777       0.00      0.00      0.00         2
       36252       0.00      0.00      0.00         7
       58338       0.00      0.00      0.00         2
       59767       0.00      0.00      0.00         4
       67618       0.00      0.00      0.00         2
       72257       0.00      0.00      0.00         1
       82352       0.00      0.00      0.00         3
       91903       0.00      0.00      0.00         1

    accuracy                           0.23      1802
   macro avg       0.03      0.04      0.03      1802
weighted avg       0.11      0.23      0.15      1802

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))